# Generated by Django 5.2.7 on 2025-10-11 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$')]),
        ),
    ]
