# Generated by Django 5.2.5 on 2025-09-12 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('translator', models.CharField(blank=True, max_length=50, verbose_name='translator')),
                ('publisher', models.CharField(blank=True, max_length=50, verbose_name='publisher')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='price')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('shabak_number', models.CharField(blank=True, help_text='Enter ISBN-13 (13 digits starting with 978 or 979)', max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid ISBN-13 (13 digits starting with 978 or 979)', regex='^(978|979)\\d{10}$')], verbose_name='ISBN-13')),
                ('status', models.CharField(choices=[('R', 'Read'), ('NR', 'Not Read'), ('B', 'Borrowed')], default='R', max_length=3)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of page')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
