# Generated by Django 5.2.6 on 2025-09-14 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shabak_number',
            field=models.CharField(blank=True, help_text='Enter ISBN-13 (13 digits starting with 978 or 979)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ISBN-13 (13 digits starting with 978 or 979)', regex='^(978|979)\\d{10}$')], verbose_name='ISBN-13'),
        ),
    ]
